--- 
- 
  apiVersion: apps/v1
  kind: Deployment
  metadata: 
    name: departmentservice
  spec: 
    replicas: 2
    selector: 
      matchLabels: 
        app: departmentservice
    template: 
      metadata: 
        labels: 
          app: departmentservice
      spec: 
        containers: 
          - 
            image: veluchamy01/departmentservice01:latest
            name: departmentservice01
            ports: 
              - 
                containerPort: 9001
            resources: 
              limits: 
                cpu: 250m
                memory: 256Mi
              requests: 
                cpu: 100m
                memory: 128Mi
        nodeSelector: 
          beta.kubernetes.io/os: linux
- 
  apiVersion: v1
  kind: Service
  metadata: 
    name: departmentservice
  spec: 
    ports: 
      - 
        port: 9001
    selector: 
      app: departmentservice
    type: LoadBalancer